/* This file is automatically generated. */
const unsigned char od_zigzag4[15][2] = {
  { 0, 1 }, { 1, 0 }, { 1, 1 }, { 0, 2 },
  { 2, 0 }, { 1, 2 }, { 0, 3 }, { 2, 1 },
  { 3, 0 }, { 1, 3 }, { 3, 1 }, { 2, 2 },
  { 2, 3 }, { 3, 2 }, { 3, 3 }
};
